GoogleOAuth:
  demo:
    redirect_uris: ["http://127.0.0.1:5000/oauth2callback"]
    redirect_uri: "http://127.0.0.1:5000/oauth2callback"
    scope:
      [
        "openid",
        "https://www.googleapis.com/auth/userinfo.profile",
        "https://www.googleapis.com/auth/userinfo.email",
      ]
  production:
    redirect_uris: ["https://oauthtest-eidnwbgjma-an.a.run.app/oauth2callback"]
    redirect_uri: "https://oauthtest-eidnwbgjma-an.a.run.app/oauth2callback"
    scope:
      [
        "openid",
        "https://www.googleapis.com/auth/userinfo.profile",
        "https://www.googleapis.com/auth/userinfo.email",
      ]
